# Generated by Django 2.2.16 on 2022-12-13 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20221212_1907'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
