# Generated by Django 2.2.16 on 2022-12-21 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20221221_0505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(help_text='Перечислите ингредиенты', through='recipes.RecipeIngredientDetails', to='recipes.Ingredient'),
        ),
    ]
